name: Check Style

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Checkout module
        uses: actions/checkout@master
      - name: Check style
        uses: Nall-chan/action-style@strict
